server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/winter_olympics_db
    username: hristiyanivanov
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    user:
      name: dev
      password: dev
      roles: USER

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

application:
  security:
    jwt:
      secret-key: 0123456789abcdef0123456789abcdef0123456789abcdef
      expiration-ms: 86400000